### ISSUE TITLE
Hardening: Implement CSP

### ISSUE THREAD

**Issue by LukasReschke** [amarfurt/hdc#49]
Since no inline JavaScript is used it should be easily possible to implement a very strict CSP policy. Using CSP will make XSS a non-issue in nearly all browsers: http://caniuse.com/#feat=contentsecuritypolicy

CSP is as easy as sending a simple header, http://cspisawesome.com/ has a nice builder for it.

My recommendations:
- Default to `none`
- Script to `self`
- Style to `self` (requires the removal of all inline CSS)
- Image, Connect, etc. to the whitelists of hosts that actually are required

**Comment by amarfurt** [comment]
Refers to version that has been moved.
